param(
    [ValidateSet(1280,1600,1920)][int]$Width=1600,
    [ValidateSet(720,900,1080)][int]$Height=900,
    [string]$EngineRoot='C:/Program Files/Epic Games/UE_5.8',
    [ValidatePattern('^[A-Za-z][A-Za-z0-9_]{0,47}$')][string]$Id='SlimeScout_v2'
)
$ErrorActionPreference='Stop'
. "$PSScriptRoot/combat-process.ps1"
$projectRoot=Split-Path $PSScriptRoot -Parent
$output=Join-Path $projectRoot "Saved/CombatAudit/Workbench/$($Width)x$($Height)"
New-Item -ItemType Directory -Force $output | Out-Null
$logFile=Join-Path $output 'game.log'
$expectedHealth=100
$resolved=Join-Path $projectRoot "CombatRecipes/$Id.resolved.json"
if(Test-Path -LiteralPath $resolved){$data=Get-Content -LiteralPath $resolved -Raw | ConvertFrom-Json;if($data.player.stats.max_health){$expectedHealth=$data.player.stats.max_health}}
$args=@(
    ('"{0}"' -f (Join-Path $projectRoot 'Constellation.uproject')),
    "/Game/Constellation/Review/CombatRecipes/$Id/L_Preview",
    '-game','-windowed','-NoDebugExecBindings',"-ResX=$Width","-ResY=$Height",'-ForceRes','-RenderOffscreen',
    '-unattended','-nop4','-nosplash','-CombatWorkbenchReview','-CombatWorkbenchApplyReview',
    "-CombatWorkbenchExpectedHealth=$expectedHealth",
    ('"-abslog={0}"' -f $logFile)
)
$started=[DateTime]::UtcNow
$presetName='Review_'+[Guid]::NewGuid().ToString('N')
$presetFile=Join-Path $projectRoot "Saved/CombatTuning/$presetName.json"
try {
    foreach($phase in @('Save','Load')){
        $phaseArgs=@($args | Where-Object {$_ -notlike '*-abslog=*'})
        $phaseLog=Join-Path $output "game-$phase.log"
        $phaseArgs+=@("-CombatWorkbenchPreset=$presetName",('"-abslog={0}"' -f $phaseLog))
        if($phase -eq 'Load'){$phaseArgs+='-CombatWorkbenchLoadPreset'}
        $process=Start-Process -FilePath (Join-Path $EngineRoot 'Engine/Binaries/Win64/UnrealEditor.exe') -ArgumentList $phaseArgs -WindowStyle Hidden -PassThru
        try {$exitCode=Wait-CombatProcess -Process $process -TimeoutSeconds 180}
        finally {$process.Dispose()}
        $log=Get-Content -LiteralPath $phaseLog -Raw
        $required=@('DodgeCancel','InputWindow','ReportImport','TuningReport','Changes','UndoChange','Restart','F1Open','F1Close','Slow','DeathOpen','DeathClose','DeathRestart',("Preset$phase"))
        $missing=@($required | Where-Object {$log -notmatch ("CombatWorkbench"+$_+"Review: PASS")})
        if($exitCode -ne 0 -or $missing.Count -gt 0 -or $log -match 'CombatWorkbench.*Review: FAIL|Fatal error:|Assertion failed:'){
            throw "Workbench review failed ($phase). Missing: $($missing -join ', '). See $phaseLog"
        }
    }
    Copy-Item -LiteralPath $phaseLog -Destination $logFile -Force
}
finally {
    foreach($phase in @('Save','Load')){
        $reportFile=Join-Path $projectRoot "Saved/CombatTuningReports/$($presetName)_$phase.json"
        if(Test-Path -LiteralPath $reportFile){
            Copy-Item -LiteralPath $reportFile -Destination (Join-Path $output "tuning-report-$phase.json") -Force
            Remove-Item -LiteralPath $reportFile
        }
    }
    # Only the unique preset generated by this invocation is removed.
    if(Test-Path -LiteralPath $presetFile){Remove-Item -LiteralPath $presetFile}
}
foreach($name in @('panel','hud','history','changes')){
    $source=Join-Path $projectRoot "Saved/Screenshots/Workbench-$name.png"
    $item=Get-Item -LiteralPath $source
    if($item.LastWriteTimeUtc -lt $started){throw "Stale screenshot: $source"}
    $bytes=[IO.File]::ReadAllBytes($source)
    $actualWidth=($bytes[16]*16777216)+($bytes[17]*65536)+($bytes[18]*256)+$bytes[19]
    $actualHeight=($bytes[20]*16777216)+($bytes[21]*65536)+($bytes[22]*256)+$bytes[23]
    if($actualWidth -ne $Width -or $actualHeight -ne $Height){throw "Screenshot size mismatch: $($actualWidth)x$($actualHeight)"}
    Copy-Item -LiteralPath $source -Destination (Join-Path $output "$name.png") -Force
}
Write-Output "PASS: change comparison/undo, F1/death lifecycle, slow mode, cross-process preset round-trip and $($Width)x$($Height) screenshots. $output"
